delete from XUATKHO
DBCC CHECKIDENT ('XUATKHO', RESEED, 0)
GO
delete from TONKHO
DBCC CHECKIDENT ('TONKHO', RESEED, 0)
GO
delete from PHIEUNHAPHANG
DBCC CHECKIDENT ('PHIEUNHAPHANG', RESEED, 0)
GO
delete from SANPHAM
delete from LOAI
delete from NHACUNGCAP