//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("quanlikhocuahangModel", "FK__SANPHAM__LOAISP__173876EA", "LOAI", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DTO.LOAI), "SANPHAM", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTO.SANPHAM), true)]
[assembly: EdmRelationshipAttribute("quanlikhocuahangModel", "FK__PHIEUNHAP__MANHA__1A14E395", "NHACUNGCAP", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DTO.NHACUNGCAP), "PHIEUNHAPHANG", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTO.PHIEUNHAPHANG), true)]
[assembly: EdmRelationshipAttribute("quanlikhocuahangModel", "FK__PHIEUNHAPH__MANV__1B0907CE", "NHANVIEN", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DTO.NHANVIEN), "PHIEUNHAPHANG", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTO.PHIEUNHAPHANG), true)]
[assembly: EdmRelationshipAttribute("quanlikhocuahangModel", "FK__TONKHO__MANHAPHA__1FCDBCEB", "PHIEUNHAPHANG", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DTO.PHIEUNHAPHANG), "TONKHO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTO.TONKHO), true)]
[assembly: EdmRelationshipAttribute("quanlikhocuahangModel", "FK__TONKHO__MASP__1ED998B2", "SANPHAM", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DTO.SANPHAM), "TONKHO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTO.TONKHO), true)]
[assembly: EdmRelationshipAttribute("quanlikhocuahangModel", "FK__XUATKHO__DONGIAX__22AA2996", "TONKHO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DTO.TONKHO), "XUATKHO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTO.XUATKHO), true)]
[assembly: EdmRelationshipAttribute("quanlikhocuahangModel", "FK__XUATKHO__MANV__34C8D9D1", "NHANVIEN", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DTO.NHANVIEN), "XUATKHO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTO.XUATKHO), true)]

#endregion

namespace DTO
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class quanlikhocuahangEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new quanlikhocuahangEntities object using the connection string found in the 'quanlikhocuahangEntities' section of the application configuration file.
        /// </summary>
        public quanlikhocuahangEntities() : base("name=quanlikhocuahangEntities", "quanlikhocuahangEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new quanlikhocuahangEntities object.
        /// </summary>
        public quanlikhocuahangEntities(string connectionString) : base(connectionString, "quanlikhocuahangEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new quanlikhocuahangEntities object.
        /// </summary>
        public quanlikhocuahangEntities(EntityConnection connection) : base(connection, "quanlikhocuahangEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LOAI> LOAIs
        {
            get
            {
                if ((_LOAIs == null))
                {
                    _LOAIs = base.CreateObjectSet<LOAI>("LOAIs");
                }
                return _LOAIs;
            }
        }
        private ObjectSet<LOAI> _LOAIs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NHACUNGCAP> NHACUNGCAPs
        {
            get
            {
                if ((_NHACUNGCAPs == null))
                {
                    _NHACUNGCAPs = base.CreateObjectSet<NHACUNGCAP>("NHACUNGCAPs");
                }
                return _NHACUNGCAPs;
            }
        }
        private ObjectSet<NHACUNGCAP> _NHACUNGCAPs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NHANVIEN> NHANVIENs
        {
            get
            {
                if ((_NHANVIENs == null))
                {
                    _NHANVIENs = base.CreateObjectSet<NHANVIEN>("NHANVIENs");
                }
                return _NHANVIENs;
            }
        }
        private ObjectSet<NHANVIEN> _NHANVIENs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PHIEUNHAPHANG> PHIEUNHAPHANGs
        {
            get
            {
                if ((_PHIEUNHAPHANGs == null))
                {
                    _PHIEUNHAPHANGs = base.CreateObjectSet<PHIEUNHAPHANG>("PHIEUNHAPHANGs");
                }
                return _PHIEUNHAPHANGs;
            }
        }
        private ObjectSet<PHIEUNHAPHANG> _PHIEUNHAPHANGs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SANPHAM> SANPHAMs
        {
            get
            {
                if ((_SANPHAMs == null))
                {
                    _SANPHAMs = base.CreateObjectSet<SANPHAM>("SANPHAMs");
                }
                return _SANPHAMs;
            }
        }
        private ObjectSet<SANPHAM> _SANPHAMs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TONKHO> TONKHOes
        {
            get
            {
                if ((_TONKHOes == null))
                {
                    _TONKHOes = base.CreateObjectSet<TONKHO>("TONKHOes");
                }
                return _TONKHOes;
            }
        }
        private ObjectSet<TONKHO> _TONKHOes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<XUATKHO> XUATKHOes
        {
            get
            {
                if ((_XUATKHOes == null))
                {
                    _XUATKHOes = base.CreateObjectSet<XUATKHO>("XUATKHOes");
                }
                return _XUATKHOes;
            }
        }
        private ObjectSet<XUATKHO> _XUATKHOes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LOAIs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLOAIs(LOAI lOAI)
        {
            base.AddObject("LOAIs", lOAI);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NHACUNGCAPs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNHACUNGCAPs(NHACUNGCAP nHACUNGCAP)
        {
            base.AddObject("NHACUNGCAPs", nHACUNGCAP);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NHANVIENs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNHANVIENs(NHANVIEN nHANVIEN)
        {
            base.AddObject("NHANVIENs", nHANVIEN);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PHIEUNHAPHANGs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPHIEUNHAPHANGs(PHIEUNHAPHANG pHIEUNHAPHANG)
        {
            base.AddObject("PHIEUNHAPHANGs", pHIEUNHAPHANG);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SANPHAMs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSANPHAMs(SANPHAM sANPHAM)
        {
            base.AddObject("SANPHAMs", sANPHAM);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TONKHOes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTONKHOes(TONKHO tONKHO)
        {
            base.AddObject("TONKHOes", tONKHO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the XUATKHOes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToXUATKHOes(XUATKHO xUATKHO)
        {
            base.AddObject("XUATKHOes", xUATKHO);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="quanlikhocuahangModel", Name="LOAI")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LOAI : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LOAI object.
        /// </summary>
        /// <param name="mALOAI">Initial value of the MALOAI property.</param>
        public static LOAI CreateLOAI(global::System.String mALOAI)
        {
            LOAI lOAI = new LOAI();
            lOAI.MALOAI = mALOAI;
            return lOAI;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MALOAI
        {
            get
            {
                return _MALOAI;
            }
            set
            {
                if (_MALOAI != value)
                {
                    OnMALOAIChanging(value);
                    ReportPropertyChanging("MALOAI");
                    _MALOAI = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MALOAI");
                    OnMALOAIChanged();
                }
            }
        }
        private global::System.String _MALOAI;
        partial void OnMALOAIChanging(global::System.String value);
        partial void OnMALOAIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TENLOAI
        {
            get
            {
                return _TENLOAI;
            }
            set
            {
                OnTENLOAIChanging(value);
                ReportPropertyChanging("TENLOAI");
                _TENLOAI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TENLOAI");
                OnTENLOAIChanged();
            }
        }
        private global::System.String _TENLOAI;
        partial void OnTENLOAIChanging(global::System.String value);
        partial void OnTENLOAIChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("quanlikhocuahangModel", "FK__SANPHAM__LOAISP__173876EA", "SANPHAM")]
        public EntityCollection<SANPHAM> SANPHAMs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SANPHAM>("quanlikhocuahangModel.FK__SANPHAM__LOAISP__173876EA", "SANPHAM");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SANPHAM>("quanlikhocuahangModel.FK__SANPHAM__LOAISP__173876EA", "SANPHAM", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="quanlikhocuahangModel", Name="NHACUNGCAP")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NHACUNGCAP : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NHACUNGCAP object.
        /// </summary>
        /// <param name="mANHACUNGCAP">Initial value of the MANHACUNGCAP property.</param>
        public static NHACUNGCAP CreateNHACUNGCAP(global::System.String mANHACUNGCAP)
        {
            NHACUNGCAP nHACUNGCAP = new NHACUNGCAP();
            nHACUNGCAP.MANHACUNGCAP = mANHACUNGCAP;
            return nHACUNGCAP;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MANHACUNGCAP
        {
            get
            {
                return _MANHACUNGCAP;
            }
            set
            {
                if (_MANHACUNGCAP != value)
                {
                    OnMANHACUNGCAPChanging(value);
                    ReportPropertyChanging("MANHACUNGCAP");
                    _MANHACUNGCAP = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MANHACUNGCAP");
                    OnMANHACUNGCAPChanged();
                }
            }
        }
        private global::System.String _MANHACUNGCAP;
        partial void OnMANHACUNGCAPChanging(global::System.String value);
        partial void OnMANHACUNGCAPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TENNHACUNGCAP
        {
            get
            {
                return _TENNHACUNGCAP;
            }
            set
            {
                OnTENNHACUNGCAPChanging(value);
                ReportPropertyChanging("TENNHACUNGCAP");
                _TENNHACUNGCAP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TENNHACUNGCAP");
                OnTENNHACUNGCAPChanged();
            }
        }
        private global::System.String _TENNHACUNGCAP;
        partial void OnTENNHACUNGCAPChanging(global::System.String value);
        partial void OnTENNHACUNGCAPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DIACHI
        {
            get
            {
                return _DIACHI;
            }
            set
            {
                OnDIACHIChanging(value);
                ReportPropertyChanging("DIACHI");
                _DIACHI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DIACHI");
                OnDIACHIChanged();
            }
        }
        private global::System.String _DIACHI;
        partial void OnDIACHIChanging(global::System.String value);
        partial void OnDIACHIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DIENTHOAI
        {
            get
            {
                return _DIENTHOAI;
            }
            set
            {
                OnDIENTHOAIChanging(value);
                ReportPropertyChanging("DIENTHOAI");
                _DIENTHOAI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DIENTHOAI");
                OnDIENTHOAIChanged();
            }
        }
        private global::System.String _DIENTHOAI;
        partial void OnDIENTHOAIChanging(global::System.String value);
        partial void OnDIENTHOAIChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("quanlikhocuahangModel", "FK__PHIEUNHAP__MANHA__1A14E395", "PHIEUNHAPHANG")]
        public EntityCollection<PHIEUNHAPHANG> PHIEUNHAPHANGs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PHIEUNHAPHANG>("quanlikhocuahangModel.FK__PHIEUNHAP__MANHA__1A14E395", "PHIEUNHAPHANG");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PHIEUNHAPHANG>("quanlikhocuahangModel.FK__PHIEUNHAP__MANHA__1A14E395", "PHIEUNHAPHANG", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="quanlikhocuahangModel", Name="NHANVIEN")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NHANVIEN : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NHANVIEN object.
        /// </summary>
        /// <param name="mANV">Initial value of the MANV property.</param>
        public static NHANVIEN CreateNHANVIEN(global::System.String mANV)
        {
            NHANVIEN nHANVIEN = new NHANVIEN();
            nHANVIEN.MANV = mANV;
            return nHANVIEN;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MANV
        {
            get
            {
                return _MANV;
            }
            set
            {
                if (_MANV != value)
                {
                    OnMANVChanging(value);
                    ReportPropertyChanging("MANV");
                    _MANV = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MANV");
                    OnMANVChanged();
                }
            }
        }
        private global::System.String _MANV;
        partial void OnMANVChanging(global::System.String value);
        partial void OnMANVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TENNV
        {
            get
            {
                return _TENNV;
            }
            set
            {
                OnTENNVChanging(value);
                ReportPropertyChanging("TENNV");
                _TENNV = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TENNV");
                OnTENNVChanged();
            }
        }
        private global::System.String _TENNV;
        partial void OnTENNVChanging(global::System.String value);
        partial void OnTENNVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DIACHI
        {
            get
            {
                return _DIACHI;
            }
            set
            {
                OnDIACHIChanging(value);
                ReportPropertyChanging("DIACHI");
                _DIACHI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DIACHI");
                OnDIACHIChanged();
            }
        }
        private global::System.String _DIACHI;
        partial void OnDIACHIChanging(global::System.String value);
        partial void OnDIACHIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DIENTHOAI
        {
            get
            {
                return _DIENTHOAI;
            }
            set
            {
                OnDIENTHOAIChanging(value);
                ReportPropertyChanging("DIENTHOAI");
                _DIENTHOAI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DIENTHOAI");
                OnDIENTHOAIChanged();
            }
        }
        private global::System.String _DIENTHOAI;
        partial void OnDIENTHOAIChanging(global::System.String value);
        partial void OnDIENTHOAIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NGAYSINH
        {
            get
            {
                return _NGAYSINH;
            }
            set
            {
                OnNGAYSINHChanging(value);
                ReportPropertyChanging("NGAYSINH");
                _NGAYSINH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NGAYSINH");
                OnNGAYSINHChanged();
            }
        }
        private Nullable<global::System.DateTime> _NGAYSINH;
        partial void OnNGAYSINHChanging(Nullable<global::System.DateTime> value);
        partial void OnNGAYSINHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MATKHAU
        {
            get
            {
                return _MATKHAU;
            }
            set
            {
                OnMATKHAUChanging(value);
                ReportPropertyChanging("MATKHAU");
                _MATKHAU = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MATKHAU");
                OnMATKHAUChanged();
            }
        }
        private global::System.String _MATKHAU;
        partial void OnMATKHAUChanging(global::System.String value);
        partial void OnMATKHAUChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> PHANQUYEN
        {
            get
            {
                return _PHANQUYEN;
            }
            set
            {
                OnPHANQUYENChanging(value);
                ReportPropertyChanging("PHANQUYEN");
                _PHANQUYEN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PHANQUYEN");
                OnPHANQUYENChanged();
            }
        }
        private Nullable<global::System.Boolean> _PHANQUYEN;
        partial void OnPHANQUYENChanging(Nullable<global::System.Boolean> value);
        partial void OnPHANQUYENChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("quanlikhocuahangModel", "FK__PHIEUNHAPH__MANV__1B0907CE", "PHIEUNHAPHANG")]
        public EntityCollection<PHIEUNHAPHANG> NHANVIENs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PHIEUNHAPHANG>("quanlikhocuahangModel.FK__PHIEUNHAPH__MANV__1B0907CE", "PHIEUNHAPHANG");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PHIEUNHAPHANG>("quanlikhocuahangModel.FK__PHIEUNHAPH__MANV__1B0907CE", "PHIEUNHAPHANG", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("quanlikhocuahangModel", "FK__XUATKHO__MANV__34C8D9D1", "XUATKHO")]
        public EntityCollection<XUATKHO> XUATKHOes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<XUATKHO>("quanlikhocuahangModel.FK__XUATKHO__MANV__34C8D9D1", "XUATKHO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<XUATKHO>("quanlikhocuahangModel.FK__XUATKHO__MANV__34C8D9D1", "XUATKHO", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="quanlikhocuahangModel", Name="PHIEUNHAPHANG")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PHIEUNHAPHANG : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PHIEUNHAPHANG object.
        /// </summary>
        /// <param name="mANHAPHANG">Initial value of the MANHAPHANG property.</param>
        public static PHIEUNHAPHANG CreatePHIEUNHAPHANG(global::System.Int32 mANHAPHANG)
        {
            PHIEUNHAPHANG pHIEUNHAPHANG = new PHIEUNHAPHANG();
            pHIEUNHAPHANG.MANHAPHANG = mANHAPHANG;
            return pHIEUNHAPHANG;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MANHAPHANG
        {
            get
            {
                return _MANHAPHANG;
            }
            set
            {
                if (_MANHAPHANG != value)
                {
                    OnMANHAPHANGChanging(value);
                    ReportPropertyChanging("MANHAPHANG");
                    _MANHAPHANG = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MANHAPHANG");
                    OnMANHAPHANGChanged();
                }
            }
        }
        private global::System.Int32 _MANHAPHANG;
        partial void OnMANHAPHANGChanging(global::System.Int32 value);
        partial void OnMANHAPHANGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NGAYNHAPHANG
        {
            get
            {
                return _NGAYNHAPHANG;
            }
            set
            {
                OnNGAYNHAPHANGChanging(value);
                ReportPropertyChanging("NGAYNHAPHANG");
                _NGAYNHAPHANG = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NGAYNHAPHANG");
                OnNGAYNHAPHANGChanged();
            }
        }
        private Nullable<global::System.DateTime> _NGAYNHAPHANG;
        partial void OnNGAYNHAPHANGChanging(Nullable<global::System.DateTime> value);
        partial void OnNGAYNHAPHANGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MANHACUNGCAP
        {
            get
            {
                return _MANHACUNGCAP;
            }
            set
            {
                OnMANHACUNGCAPChanging(value);
                ReportPropertyChanging("MANHACUNGCAP");
                _MANHACUNGCAP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MANHACUNGCAP");
                OnMANHACUNGCAPChanged();
            }
        }
        private global::System.String _MANHACUNGCAP;
        partial void OnMANHACUNGCAPChanging(global::System.String value);
        partial void OnMANHACUNGCAPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MANV
        {
            get
            {
                return _MANV;
            }
            set
            {
                OnMANVChanging(value);
                ReportPropertyChanging("MANV");
                _MANV = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MANV");
                OnMANVChanged();
            }
        }
        private global::System.String _MANV;
        partial void OnMANVChanging(global::System.String value);
        partial void OnMANVChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("quanlikhocuahangModel", "FK__PHIEUNHAP__MANHA__1A14E395", "NHACUNGCAP")]
        public NHACUNGCAP NHACUNGCAP
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NHACUNGCAP>("quanlikhocuahangModel.FK__PHIEUNHAP__MANHA__1A14E395", "NHACUNGCAP").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NHACUNGCAP>("quanlikhocuahangModel.FK__PHIEUNHAP__MANHA__1A14E395", "NHACUNGCAP").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NHACUNGCAP> NHACUNGCAPReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NHACUNGCAP>("quanlikhocuahangModel.FK__PHIEUNHAP__MANHA__1A14E395", "NHACUNGCAP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NHACUNGCAP>("quanlikhocuahangModel.FK__PHIEUNHAP__MANHA__1A14E395", "NHACUNGCAP", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("quanlikhocuahangModel", "FK__PHIEUNHAPH__MANV__1B0907CE", "NHANVIEN")]
        public NHANVIEN NHANVIEN
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NHANVIEN>("quanlikhocuahangModel.FK__PHIEUNHAPH__MANV__1B0907CE", "NHANVIEN").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NHANVIEN>("quanlikhocuahangModel.FK__PHIEUNHAPH__MANV__1B0907CE", "NHANVIEN").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NHANVIEN> NHANVIENReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NHANVIEN>("quanlikhocuahangModel.FK__PHIEUNHAPH__MANV__1B0907CE", "NHANVIEN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NHANVIEN>("quanlikhocuahangModel.FK__PHIEUNHAPH__MANV__1B0907CE", "NHANVIEN", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("quanlikhocuahangModel", "FK__TONKHO__MANHAPHA__1FCDBCEB", "TONKHO")]
        public EntityCollection<TONKHO> TONKHOes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TONKHO>("quanlikhocuahangModel.FK__TONKHO__MANHAPHA__1FCDBCEB", "TONKHO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TONKHO>("quanlikhocuahangModel.FK__TONKHO__MANHAPHA__1FCDBCEB", "TONKHO", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="quanlikhocuahangModel", Name="SANPHAM")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SANPHAM : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SANPHAM object.
        /// </summary>
        /// <param name="mASP">Initial value of the MASP property.</param>
        public static SANPHAM CreateSANPHAM(global::System.String mASP)
        {
            SANPHAM sANPHAM = new SANPHAM();
            sANPHAM.MASP = mASP;
            return sANPHAM;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MASP
        {
            get
            {
                return _MASP;
            }
            set
            {
                if (_MASP != value)
                {
                    OnMASPChanging(value);
                    ReportPropertyChanging("MASP");
                    _MASP = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MASP");
                    OnMASPChanged();
                }
            }
        }
        private global::System.String _MASP;
        partial void OnMASPChanging(global::System.String value);
        partial void OnMASPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HINHANH
        {
            get
            {
                return _HINHANH;
            }
            set
            {
                OnHINHANHChanging(value);
                ReportPropertyChanging("HINHANH");
                _HINHANH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HINHANH");
                OnHINHANHChanged();
            }
        }
        private global::System.String _HINHANH;
        partial void OnHINHANHChanging(global::System.String value);
        partial void OnHINHANHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TENSP
        {
            get
            {
                return _TENSP;
            }
            set
            {
                OnTENSPChanging(value);
                ReportPropertyChanging("TENSP");
                _TENSP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TENSP");
                OnTENSPChanged();
            }
        }
        private global::System.String _TENSP;
        partial void OnTENSPChanging(global::System.String value);
        partial void OnTENSPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LOAISP
        {
            get
            {
                return _LOAISP;
            }
            set
            {
                OnLOAISPChanging(value);
                ReportPropertyChanging("LOAISP");
                _LOAISP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LOAISP");
                OnLOAISPChanged();
            }
        }
        private global::System.String _LOAISP;
        partial void OnLOAISPChanging(global::System.String value);
        partial void OnLOAISPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HANSUDUNG
        {
            get
            {
                return _HANSUDUNG;
            }
            set
            {
                OnHANSUDUNGChanging(value);
                ReportPropertyChanging("HANSUDUNG");
                _HANSUDUNG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HANSUDUNG");
                OnHANSUDUNGChanged();
            }
        }
        private global::System.String _HANSUDUNG;
        partial void OnHANSUDUNGChanging(global::System.String value);
        partial void OnHANSUDUNGChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("quanlikhocuahangModel", "FK__SANPHAM__LOAISP__173876EA", "LOAI")]
        public LOAI LOAI
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LOAI>("quanlikhocuahangModel.FK__SANPHAM__LOAISP__173876EA", "LOAI").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LOAI>("quanlikhocuahangModel.FK__SANPHAM__LOAISP__173876EA", "LOAI").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LOAI> LOAIReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LOAI>("quanlikhocuahangModel.FK__SANPHAM__LOAISP__173876EA", "LOAI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LOAI>("quanlikhocuahangModel.FK__SANPHAM__LOAISP__173876EA", "LOAI", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("quanlikhocuahangModel", "FK__TONKHO__MASP__1ED998B2", "TONKHO")]
        public EntityCollection<TONKHO> TONKHOes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TONKHO>("quanlikhocuahangModel.FK__TONKHO__MASP__1ED998B2", "TONKHO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TONKHO>("quanlikhocuahangModel.FK__TONKHO__MASP__1ED998B2", "TONKHO", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="quanlikhocuahangModel", Name="TONKHO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TONKHO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TONKHO object.
        /// </summary>
        /// <param name="sTT">Initial value of the STT property.</param>
        /// <param name="mANHAPHANG">Initial value of the MANHAPHANG property.</param>
        /// <param name="mASP">Initial value of the MASP property.</param>
        public static TONKHO CreateTONKHO(global::System.Int32 sTT, global::System.Int32 mANHAPHANG, global::System.String mASP)
        {
            TONKHO tONKHO = new TONKHO();
            tONKHO.STT = sTT;
            tONKHO.MANHAPHANG = mANHAPHANG;
            tONKHO.MASP = mASP;
            return tONKHO;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 STT
        {
            get
            {
                return _STT;
            }
            set
            {
                if (_STT != value)
                {
                    OnSTTChanging(value);
                    ReportPropertyChanging("STT");
                    _STT = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("STT");
                    OnSTTChanged();
                }
            }
        }
        private global::System.Int32 _STT;
        partial void OnSTTChanging(global::System.Int32 value);
        partial void OnSTTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MANHAPHANG
        {
            get
            {
                return _MANHAPHANG;
            }
            set
            {
                OnMANHAPHANGChanging(value);
                ReportPropertyChanging("MANHAPHANG");
                _MANHAPHANG = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MANHAPHANG");
                OnMANHAPHANGChanged();
            }
        }
        private global::System.Int32 _MANHAPHANG;
        partial void OnMANHAPHANGChanging(global::System.Int32 value);
        partial void OnMANHAPHANGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MASP
        {
            get
            {
                return _MASP;
            }
            set
            {
                OnMASPChanging(value);
                ReportPropertyChanging("MASP");
                _MASP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MASP");
                OnMASPChanged();
            }
        }
        private global::System.String _MASP;
        partial void OnMASPChanging(global::System.String value);
        partial void OnMASPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NGAYHETHAN
        {
            get
            {
                return _NGAYHETHAN;
            }
            set
            {
                OnNGAYHETHANChanging(value);
                ReportPropertyChanging("NGAYHETHAN");
                _NGAYHETHAN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NGAYHETHAN");
                OnNGAYHETHANChanged();
            }
        }
        private Nullable<global::System.DateTime> _NGAYHETHAN;
        partial void OnNGAYHETHANChanging(Nullable<global::System.DateTime> value);
        partial void OnNGAYHETHANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SOLUONGNHAP
        {
            get
            {
                return _SOLUONGNHAP;
            }
            set
            {
                OnSOLUONGNHAPChanging(value);
                ReportPropertyChanging("SOLUONGNHAP");
                _SOLUONGNHAP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SOLUONGNHAP");
                OnSOLUONGNHAPChanged();
            }
        }
        private Nullable<global::System.Int32> _SOLUONGNHAP;
        partial void OnSOLUONGNHAPChanging(Nullable<global::System.Int32> value);
        partial void OnSOLUONGNHAPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SOLUONGTON
        {
            get
            {
                return _SOLUONGTON;
            }
            set
            {
                OnSOLUONGTONChanging(value);
                ReportPropertyChanging("SOLUONGTON");
                _SOLUONGTON = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SOLUONGTON");
                OnSOLUONGTONChanged();
            }
        }
        private Nullable<global::System.Int32> _SOLUONGTON;
        partial void OnSOLUONGTONChanging(Nullable<global::System.Int32> value);
        partial void OnSOLUONGTONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DONGIANHAP
        {
            get
            {
                return _DONGIANHAP;
            }
            set
            {
                OnDONGIANHAPChanging(value);
                ReportPropertyChanging("DONGIANHAP");
                _DONGIANHAP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DONGIANHAP");
                OnDONGIANHAPChanged();
            }
        }
        private Nullable<global::System.Decimal> _DONGIANHAP;
        partial void OnDONGIANHAPChanging(Nullable<global::System.Decimal> value);
        partial void OnDONGIANHAPChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("quanlikhocuahangModel", "FK__TONKHO__MANHAPHA__1FCDBCEB", "PHIEUNHAPHANG")]
        public PHIEUNHAPHANG PHIEUNHAPHANG
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PHIEUNHAPHANG>("quanlikhocuahangModel.FK__TONKHO__MANHAPHA__1FCDBCEB", "PHIEUNHAPHANG").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PHIEUNHAPHANG>("quanlikhocuahangModel.FK__TONKHO__MANHAPHA__1FCDBCEB", "PHIEUNHAPHANG").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PHIEUNHAPHANG> PHIEUNHAPHANGReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PHIEUNHAPHANG>("quanlikhocuahangModel.FK__TONKHO__MANHAPHA__1FCDBCEB", "PHIEUNHAPHANG");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PHIEUNHAPHANG>("quanlikhocuahangModel.FK__TONKHO__MANHAPHA__1FCDBCEB", "PHIEUNHAPHANG", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("quanlikhocuahangModel", "FK__TONKHO__MASP__1ED998B2", "SANPHAM")]
        public SANPHAM SANPHAM
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SANPHAM>("quanlikhocuahangModel.FK__TONKHO__MASP__1ED998B2", "SANPHAM").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SANPHAM>("quanlikhocuahangModel.FK__TONKHO__MASP__1ED998B2", "SANPHAM").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SANPHAM> SANPHAMReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SANPHAM>("quanlikhocuahangModel.FK__TONKHO__MASP__1ED998B2", "SANPHAM");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SANPHAM>("quanlikhocuahangModel.FK__TONKHO__MASP__1ED998B2", "SANPHAM", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("quanlikhocuahangModel", "FK__XUATKHO__DONGIAX__22AA2996", "XUATKHO")]
        public EntityCollection<XUATKHO> XUATKHOes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<XUATKHO>("quanlikhocuahangModel.FK__XUATKHO__DONGIAX__22AA2996", "XUATKHO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<XUATKHO>("quanlikhocuahangModel.FK__XUATKHO__DONGIAX__22AA2996", "XUATKHO", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="quanlikhocuahangModel", Name="XUATKHO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class XUATKHO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new XUATKHO object.
        /// </summary>
        /// <param name="sTT">Initial value of the STT property.</param>
        /// <param name="mATONKHO">Initial value of the MATONKHO property.</param>
        public static XUATKHO CreateXUATKHO(global::System.Int32 sTT, global::System.Int32 mATONKHO)
        {
            XUATKHO xUATKHO = new XUATKHO();
            xUATKHO.STT = sTT;
            xUATKHO.MATONKHO = mATONKHO;
            return xUATKHO;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 STT
        {
            get
            {
                return _STT;
            }
            set
            {
                if (_STT != value)
                {
                    OnSTTChanging(value);
                    ReportPropertyChanging("STT");
                    _STT = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("STT");
                    OnSTTChanged();
                }
            }
        }
        private global::System.Int32 _STT;
        partial void OnSTTChanging(global::System.Int32 value);
        partial void OnSTTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MATONKHO
        {
            get
            {
                return _MATONKHO;
            }
            set
            {
                OnMATONKHOChanging(value);
                ReportPropertyChanging("MATONKHO");
                _MATONKHO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MATONKHO");
                OnMATONKHOChanged();
            }
        }
        private global::System.Int32 _MATONKHO;
        partial void OnMATONKHOChanging(global::System.Int32 value);
        partial void OnMATONKHOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SOLUONGXUAT
        {
            get
            {
                return _SOLUONGXUAT;
            }
            set
            {
                OnSOLUONGXUATChanging(value);
                ReportPropertyChanging("SOLUONGXUAT");
                _SOLUONGXUAT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SOLUONGXUAT");
                OnSOLUONGXUATChanged();
            }
        }
        private Nullable<global::System.Int32> _SOLUONGXUAT;
        partial void OnSOLUONGXUATChanging(Nullable<global::System.Int32> value);
        partial void OnSOLUONGXUATChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NGAYXUAT
        {
            get
            {
                return _NGAYXUAT;
            }
            set
            {
                OnNGAYXUATChanging(value);
                ReportPropertyChanging("NGAYXUAT");
                _NGAYXUAT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NGAYXUAT");
                OnNGAYXUATChanged();
            }
        }
        private Nullable<global::System.DateTime> _NGAYXUAT;
        partial void OnNGAYXUATChanging(Nullable<global::System.DateTime> value);
        partial void OnNGAYXUATChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DONGIAXUAT
        {
            get
            {
                return _DONGIAXUAT;
            }
            set
            {
                OnDONGIAXUATChanging(value);
                ReportPropertyChanging("DONGIAXUAT");
                _DONGIAXUAT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DONGIAXUAT");
                OnDONGIAXUATChanged();
            }
        }
        private Nullable<global::System.Decimal> _DONGIAXUAT;
        partial void OnDONGIAXUATChanging(Nullable<global::System.Decimal> value);
        partial void OnDONGIAXUATChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MANV
        {
            get
            {
                return _MANV;
            }
            set
            {
                OnMANVChanging(value);
                ReportPropertyChanging("MANV");
                _MANV = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MANV");
                OnMANVChanged();
            }
        }
        private global::System.String _MANV;
        partial void OnMANVChanging(global::System.String value);
        partial void OnMANVChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("quanlikhocuahangModel", "FK__XUATKHO__DONGIAX__22AA2996", "TONKHO")]
        public TONKHO TONKHO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TONKHO>("quanlikhocuahangModel.FK__XUATKHO__DONGIAX__22AA2996", "TONKHO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TONKHO>("quanlikhocuahangModel.FK__XUATKHO__DONGIAX__22AA2996", "TONKHO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TONKHO> TONKHOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TONKHO>("quanlikhocuahangModel.FK__XUATKHO__DONGIAX__22AA2996", "TONKHO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TONKHO>("quanlikhocuahangModel.FK__XUATKHO__DONGIAX__22AA2996", "TONKHO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("quanlikhocuahangModel", "FK__XUATKHO__MANV__34C8D9D1", "NHANVIEN")]
        public NHANVIEN NHANVIEN
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NHANVIEN>("quanlikhocuahangModel.FK__XUATKHO__MANV__34C8D9D1", "NHANVIEN").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NHANVIEN>("quanlikhocuahangModel.FK__XUATKHO__MANV__34C8D9D1", "NHANVIEN").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NHANVIEN> NHANVIENReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NHANVIEN>("quanlikhocuahangModel.FK__XUATKHO__MANV__34C8D9D1", "NHANVIEN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NHANVIEN>("quanlikhocuahangModel.FK__XUATKHO__MANV__34C8D9D1", "NHANVIEN", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
